# Generated by Django 4.0 on 2024-03-10 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('image', models.ImageField(upload_to='product_images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Analyzer.category')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Analyzer.product')),
            ],
        ),
        migrations.CreateModel(
            name='Verdict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Analyzer.review')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=3)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Analyzer.review')),
            ],
        ),
        migrations.CreateModel(
            name='OverallRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive_reviews', models.PositiveIntegerField(default=0)),
                ('negative_reviews', models.PositiveIntegerField(default=0)),
                ('neutral_reviews', models.PositiveIntegerField(default=0)),
                ('final_verdict', models.TextField()),
                ('overall_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Analyzer.product')),
            ],
        ),
    ]
